services:
    serene-ui:
        build:
            context: .
            dockerfile: Dockerfile.test
        container_name: serene-ui
        ports:
            - "3636:3000"
            - "6543:6543"
        volumes:
            - ./apps/web/screenshots:/test-app/apps/web/screenshots
        restart: unless-stopped
    test-database:
        image: postgres:17
        ports:
            - "6363:5432"
        restart: unless-stopped
